AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Advent of Code Problem {{ cookiecutter.problem_number }} {{ cookiecutter.advent_of_code_year}}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 256


Resources:
  ProblemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: rust-cargolambda # More info about Cargo Lambda: https://github.com/cargo-lambda/cargo-lambda
    Properties:
      CodeUri: ./app   # Points to dir of Cargo.toml
      Handler: bootstrap    # Do not change, as this is the default executable name produced by Cargo Lambda
      Runtime: provided.al2023
      {%- if cookiecutter.architecture.value != []%}
      Architectures:
      {%- for arch in cookiecutter.architecture.value %}
        - {{arch}}
      {%- endfor %}
      {%- endif %}
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /problem${{ cookiecutter.problem_number }}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ProblemFunction:
    Description: "Advent of Code 2023 Problem ${{ cookiecutter.problem_number }} Lambda Function ARN"
    Value: !GetAtt ProblemFunction.Arn
  ProblemFunctionIamRole:
    Description: "Implicit IAM Role created for Advent of Code 2023 Problem ${{ cookiecutter.problem_number }} Lambda"
    Value: !GetAtt ProblemFunctionRole.Arn
